spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://localhost:3306/zacharychao?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8001
